SELECT EmpId,Empname,Deptid from Employee where Deptid=
(Select deptid from DEPT where Dname = 'ADMIN')
 
 
Select EmpId,Empname,Job from Employee where job = 
(Select job from Employee where Empname = 'SMITH')
 
 
<--employees whose salary is more than the highest salary of the emp working as Developer -->
 
Select * from Employee where Salary > 
(Select MAX(Salary) from Employee where Job='DEVELOPER')
 
Select MAX(Salary) from Employee where Job='DEVELOPER'
 
<!-- Employee whose job is same as Harry and who are earning more than Harry
 
Select * from Employee where Job = (Select Job from Employee where  Empname ='Dick') 
and Salary > (Select Salary from Employee where Empname ='Dick')
 
 
<!--Employee whose is paid the highest -->
 
Select * from Employee where Salary =
(Select MAX(salary) from Employee)
 
 
<!--Employee whose is paid the second highest -->
 
Select * from Employee where Salary = 
(Select MAX(salary) from Employee where Salary < (Select MAX(salary) from Employee ))
 
 
<!-- update employee - dick with highest salary -->
 
Update Employee set Salary = (Select MAX(salary) from Employee)  where Empid=102;
 
<!-- Delete Employee - job is same as SMITH -->
 
DELETE from Employee where Job= (Select Job from Employee where Empname='SMITH')


use TechShop

select * from Customers
select * from Orders
select * from Products
select * from Inventory
select * from OrderDetails


1. Write an SQL query to find out which customers have not placed any orders.

Select CONCAT(firstname,' ' ,lastname) as NamesHavingNoOrders from Customers
where CustomerID Not in (Select customerID from orders)

2. Write an SQL query to find the total number of products available for sale.

Select sum(QuantityInStock) from Inventory

3. Write an SQL query to calculate the total revenue generated by TechShop.

Select ProductID,
QuantityInStock*(select price from Products where Inventory.ProductID=Products.ProductID) 
from Inventory 


6. Write an SQL query to find the customers who have placed the most orders. List their names
and the number of orders they have placed.

Select Concat(FirstName,' ' ,lastname),
(Select count(customerId) as Counts from orders where customers.customerID = orders.customerID  group by customerID   ) 
from Customers


7. Write an SQL query to find the most popular product category, which is the one with the highest
total quantity ordered across all orders.

Select productID,Sum(QuantityINStock) as TotalQty from Inventory
group by productID
having Sum(Quantityinstock)=(select max(TotalQuan) from 
(
Select Sum(QuantityINStock) as TotalQuan from Inventory
group by productID
) as T
)


8. Write an SQL query to find the customer who has spent the most money (highest total revenue)
on electronic gadgets. List their name and total spending.


Select Concat(FirstName,' ' ,lastname),
(Select Sum(TotalAmount)  from orders 
where customers.customerID = orders.customerID  group by customerID   ) as Revenue
from Customers 
order by revenue desc


9. Write an SQL query to calculate the average order value (total revenue divided by the number of
orders) for all customers.

Select Sum(TotalAmount)/count(orderid)  from orders

10. Write an SQL query to find the total number of orders placed by each customer and list their
names along with the order count.

Select Concat(FirstName,' ' ,lastname) as Customer_Name,
(Select Sum(TotalAmount)  from orders 
where customers.customerID = orders.customerID  group by customerID   ) as TotalAmount,
(Select count(customerId) from orders 
where customers.customerID = orders.customerID  group by customerID  ) as OrderCount
from Customers 
order by TotalAmount desc
